project_id = "sfgwaukvjwcwdvnxklod"

[functions.generate-blog-post]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.optimize-seo]
verify_jwt = false

[functions.seo-chat]
verify_jwt = false

[functions.auto-generate-blog]
verify_jwt = false