// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfgwaukvjwcwdvnxklod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmZ3dhdWt2andjd2R2bnhrbG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjQyNTcsImV4cCI6MjA3MjE0MDI1N30.bM2hbn8mycmjv5Uqeax1zblJEHZrF-l39dCUBVjjCBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// iOS 26 Safari fix: Custom fetch with retry logic and timeout
const customFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 10000);
  
  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal,
      credentials: 'same-origin',
      mode: 'cors',
      cache: 'no-cache'
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error) {
    clearTimeout(timeoutId);
    console.log('Fetch failed, retrying...', error);
    await new Promise(resolve => setTimeout(resolve, 500));
    return fetch(url, {
      ...options,
      credentials: 'same-origin',
      mode: 'cors',
      cache: 'no-cache'
    });
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // iOS 26 Safari fix
  },
  global: {
    fetch: customFetch,
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});